import "example";

// comment, comment \n


func foo(x: i32, y: u32) u64 {
    return u64(y + u32(x));
}

-131439482490

-123879.232138E-1837829

func main() int {

    _ = foo(1000, 999);

    var x: bool;
    var bar := example::Bar{y = 10, x = 111};

    x = bar.Foo(1984, 1984);

    if x {
        var y: *u32 = new<u32>(10);
        defer delete(y);

        std::println(bar.Bar(y, u64(*y)));
    }



    return 0;
}

dsgfhlsdfajf;oidjhjgj 1823798410481







